version: "3"
services:
  mssql: 
    image: "microsoft/mssql-server-linux:2017-latest"
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "SqlDevOps20!7"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
    volumes:
      - /home/ro/Databases/mssql:/var/opt/mssql      
